"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type PathId = "money" | "academic" | "basic" | "burnout" | "family" | "safety";
type Choice = { text: string; feedback: string; strong: boolean };
type Scene = { title: string; message: string; coach: string; choices: Choice[] };
type Pathway = { id: PathId; icon: string; label: string; summary: string; color: string; opening: string; scenes: Scene[]; template: string; resources: Array<{ label: string; detail: string; href: string }> };

const sharedScenes: Scene[] = [
  { title: "Start with care—not a solution", message: "I don’t think I can do this anymore. I might just leave school.", coach: "Your first job is to make it safer for Jordan to keep talking.", choices: [
    { text: "That sounds really heavy. I’m glad you told me. What’s making school feel impossible right now?", feedback: "Strong start. You acknowledge the weight of the situation and ask an open question without taking control.", strong: true },
    { text: "You can’t drop out—you’ve already come too far.", feedback: "The intention is caring, but this can make Jordan feel judged or trapped. Begin by listening before persuading.", strong: false },
    { text: "Everybody feels like that sometimes. You’ll be fine.", feedback: "This minimizes what Jordan shared. Their situation deserves curiosity, not comparison.", strong: false },
  ]},
  { title: "Ask what kind of support they want", message: "I don’t even know where to start. Everything feels connected.", coach: "Support works better when you ask permission before problem-solving.", choices: [
    { text: "Do you want me to listen, help you think through options, or sit with you while we contact someone?", feedback: "Excellent. Jordan keeps ownership while learning that they do not have to take the next step alone.", strong: true },
    { text: "Give me your phone. I’ll email the dean and handle it.", feedback: "Taking over can make someone feel powerless. Offer to do the task with them, not for them, unless safety requires immediate action.", strong: false },
    { text: "You should make a list of everything that’s wrong.", feedback: "A list may help later, but this response adds another assignment before Jordan feels heard.", strong: false },
  ]},
];

const pathways: Pathway[] = [
  { id: "money", icon: "$", label: "Tuition or financial-aid crisis", color: "sun", summary: "A balance, aid change, or registration hold is pushing them out.", opening: "My aid changed, I owe $2,400, and they said I can’t register. I feel stupid for thinking I could afford this.", scenes: [{ title: "Turn panic into one next move", message: "The deadline is Friday. I don’t think there’s anything I can do.", coach: "Do not promise money or a result. Help Jordan protect their options before withdrawing.", choices: [
    { text: "Let’s look at the notice together and identify who can change the decision. I can sit with you while you contact financial aid or the dean of students.", feedback: "Strong. You offer practical company, preserve Jordan’s agency, and focus on the office with decision-making power.", strong: true },
    { text: "Start a fundraiser tonight. That’s probably the only way.", feedback: "Fundraising may be one tool, but it should not replace checking appeals, emergency grants, payment options, and institutional errors first.", strong: false },
    { text: "Maybe taking the semester off is for the best.", feedback: "A pause may eventually be Jordan’s choice, but recommend it only after they understand the academic and financial consequences.", strong: false },
  ]}], template: "Hey Jordan, I’m glad you told me. A balance does not mean you failed. Before you withdraw, can we look at the notice together and identify the deadline and the office that can change the decision? I can sit with you while you contact financial aid, student accounts, or the dean of students. You deserve to know every option before making a permanent decision.", resources: [
    { label: "Tuition Rescue Plan", detail: "Build a personalized 48-hour response.", href: "/tools/balance" }, { label: "Student Defense Suite", detail: "Prepare an appeal, evidence, and escalation path.", href: "/defense?tool=tuition" }, { label: "Federal Student Aid", detail: "Review official aid and FAFSA guidance.", href: "https://studentaid.gov/" },
  ]},
  { id: "academic", icon: "A+", label: "Grades or academic standing", color: "coral", summary: "Failing classes, SAP, probation, or fear of disappointing others.", opening: "I’m failing two classes. If my family finds out, I’m done. It feels easier to disappear before everybody knows.", scenes: [{ title: "Separate the semester from the person", message: "I already messed everything up. There is no fixing this.", coach: "Shame makes help harder to reach. Validate the fear and guide Jordan toward accurate information.", choices: [
    { text: "This semester is a situation—not your identity. Would it help if we checked the academic deadlines and talked with your professor or advisor together?", feedback: "Strong. You reduce shame without making false promises and offer a specific, shared next step.", strong: true },
    { text: "You just need to study harder this week.", feedback: "This assumes effort is the only barrier and may deepen shame. Learn what is happening before offering a strategy.", strong: false },
    { text: "Don’t tell your family. We can keep this between us.", feedback: "Do not promise secrecy. Help Jordan decide which safe, supportive person or professional can join the plan.", strong: false },
  ]}], template: "I hear how ashamed and scared you feel, but one hard semester is not your whole story. Before you disappear or withdraw, can we check your deadlines and options together? I can sit with you while you email your professor, advisor, tutoring center, or academic-success office. We only need one next step today.", resources: [
    { label: "Stay-Enrolled Planner", detail: "Name the barrier and build a support-team plan.", href: "/tools/persist" }, { label: "Student Defense Suite", detail: "Navigate grades, SAP, and academic petitions.", href: "/defense?tool=sap" }, { label: "Reach for Yourself", detail: "Build a complete stay-enrolled plan.", href: "/reach-yourself" },
  ]},
  { id: "basic", icon: "⌂", label: "Food, housing, or transportation", color: "mint", summary: "A basic need is making school attendance impossible.", opening: "I’m sleeping on somebody’s couch and missing class because I don’t have a ride. I can’t keep pretending everything is normal.", scenes: [{ title: "Stabilize the next 24 hours", message: "I don’t want everybody in my business. I just need somewhere safe tonight.", coach: "Respect privacy while connecting Jordan to urgent, practical support.", choices: [
    { text: "You control who knows. Let’s focus on tonight first—would you like me to sit with you while we call 211 or your campus basic-needs office?", feedback: "Strong. You protect dignity, prioritize the immediate need, and offer company without forcing disclosure.", strong: true },
    { text: "You can stay with me as long as you need.", feedback: "A short offer may be generous, but do not promise housing beyond your capacity. Pair personal help with stable resources.", strong: false },
    { text: "You should have told someone earlier.", feedback: "This adds blame when Jordan needs safety. Focus on what can happen next.", strong: false },
  ]}], template: "Thank you for trusting me. You do not have to explain everything or tell everybody. Let’s focus on the most urgent need first. Would you like me to stay with you while we call 211 or contact the campus basic-needs, housing, or student-affairs office? We can take the rest one step at a time.", resources: [
    { label: "Call 211", detail: "Find local food, housing, utilities, and transportation support.", href: "https://www.211.org/" }, { label: "FindHelp", detail: "Search nearby free and reduced-cost programs.", href: "https://www.findhelp.org/" }, { label: "EFF Student Resources", detail: "Open EFF’s organized support directory.", href: "https://portal.estherfundsfoundation.org/resources" },
  ]},
  { id: "burnout", icon: "♡", label: "Burnout, isolation, or belonging", color: "lilac", summary: "They feel exhausted, alone, or as if college was not made for them.", opening: "Everybody else looks like they belong here. I’m exhausted from acting like I’m okay. Maybe college just isn’t for people like me.", scenes: [{ title: "Make room for the real feeling", message: "I don’t need a motivational speech. I’m just tired.", coach: "Presence can be more helpful than positivity. Let Jordan decide what support sounds like.", choices: [
    { text: "No speech. I can just sit with you. What has been draining you the most—and what would make this week feel even 5% lighter?", feedback: "Strong. You honor the boundary, invite specifics, and make the next step feel manageable.", strong: true },
    { text: "Think positive. You earned your place here.", feedback: "The encouragement is kind, but it skips over the exhaustion Jordan asked you to acknowledge.", strong: false },
    { text: "You need counseling.", feedback: "Counseling can help, but leading with a directive may feel dismissive. Listen first, then ask permission to explore support.", strong: false },
  ]}], template: "I hear you. I’m not going to give you a motivational speech or make you prove how hard this is. I can sit with you and listen. What has been draining you the most, and what would make this week feel even a little lighter? If you want, we can look at counseling, mentoring, accommodations, or one trusted campus person together.", resources: [
    { label: "Reach for Yourself", detail: "Find wellness, belonging, and student-support options.", href: "/reach-yourself" }, { label: "Find a Health Center", detail: "Locate community health services.", href: "https://findahealthcenter.hrsa.gov/" }, { label: "988 Lifeline", detail: "Call or text 988 if distress becomes a crisis.", href: "https://988lifeline.org/" },
  ]},
  { id: "family", icon: "↔", label: "Family, work, or caregiving pressure", color: "sun", summary: "Responsibilities outside school are crowding out their education.", opening: "My family needs my paycheck and my little brother needs me. I’m working nights and sleeping through class. Something has to go.", scenes: [{ title: "Respect the responsibility", message: "School people don’t understand. I can’t just stop helping my family.", coach: "Do not frame family responsibilities as a bad choice. Look for flexibility and support.", choices: [
    { text: "Your family matters, and so does the future you’re building. Can we explore options that respect both—like a course adjustment, emergency support, childcare, or a work-study conversation?", feedback: "Strong. You respect Jordan’s values and invite solutions without demanding that they abandon family responsibilities.", strong: true },
    { text: "Your education has to come first, no matter what.", feedback: "This dismisses real obligations. Support Jordan in finding a sustainable balance rather than ranking what they love.", strong: false },
    { text: "Quit your job and apply for more loans.", feedback: "This creates financial risk and may be impossible. Explore grants, benefits, scheduling, and campus support before debt.", strong: false },
  ]}], template: "I respect how much you are carrying for your family. You should not have to choose without knowing every option. Can we explore one change that protects both your responsibilities and your education—such as a course adjustment, emergency aid, childcare, benefits, work-study, or a conversation with the dean of students? I can go with you.", resources: [
    { label: "Family Funding Check", detail: "Pressure-test the college gap and borrowing choices.", href: "/tools/family" }, { label: "Childcare Assistance", detail: "Find state and local childcare support.", href: "https://www.childcare.gov/consumer-education/get-help-paying-for-child-care/child-care-financial-assistance-options" }, { label: "CareerOneStop", detail: "Explore work, training, and local employment resources.", href: "https://www.careeronestop.org/" },
  ]},
  { id: "safety", icon: "!", label: "Urgent safety or mental-health concern", color: "coral", summary: "Their words or behavior suggest they may not be safe.", opening: "I don’t care what happens anymore. Everybody would be better off if I just disappeared.", scenes: [{ title: "Ask directly and stay present", message: "Please don’t make this a big deal. Promise you won’t tell anyone.", coach: "Safety comes before secrecy. Asking about suicide does not plant the idea.", choices: [
    { text: "I care about you too much to promise secrecy. Are you thinking about suicide or hurting yourself right now? I’m staying with you while we call or text 988.", feedback: "Strong. You ask directly, do not leave Jordan alone, and connect to immediate professional support.", strong: true },
    { text: "Promise me you won’t do anything, okay?", feedback: "A promise is not a safety plan. Ask directly, stay present, and involve trained support immediately.", strong: false },
    { text: "You’re scaring me. Don’t say things like that.", feedback: "This may shut down disclosure. Stay calm, acknowledge what you heard, and get immediate help.", strong: false },
  ]}], template: "I’m really glad you told me. I care about you too much to keep this secret. Are you thinking about suicide or hurting yourself right now? I am staying with you while we call or text 988. If you are in immediate danger, have a plan, or cannot stay safe, I’m calling 911 or campus emergency services now.", resources: [
    { label: "Call or text 988", detail: "24/7 Suicide & Crisis Lifeline support.", href: "https://988lifeline.org/" }, { label: "Call 911", detail: "Use for immediate danger or a life-threatening emergency.", href: "tel:911" }, { label: "Crisis Text Line", detail: "Text HOME to 741741.", href: "https://www.crisistextline.org/" },
  ]},
];

const stages = ["Notice", "Listen", "Ask", "Connect", "Follow up"];

export default function FriendWalkthrough() {
  const [selected, setSelected] = useState<Pathway | null>(null);
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<number[]>([]);
  const [picked, setPicked] = useState<number | null>(null);
  const [copied, setCopied] = useState(false);
  const scenes = useMemo(() => selected ? [sharedScenes[0], { ...sharedScenes[1], message: selected.opening }, ...selected.scenes] : [], [selected]);
  const finished = Boolean(selected && step >= scenes.length);
  const score = answers.reduce((total, answer, index) => total + (scenes[index]?.choices[answer]?.strong ? 1 : 0), 0);

  function choosePath(path: Pathway) { setSelected(path); setStep(0); setAnswers([]); setPicked(null); setCopied(false); }
  function next() { if (picked === null) return; setAnswers([...answers, picked]); setStep(step + 1); setPicked(null); }
  async function copyTemplate() { if (!selected) return; await navigator.clipboard.writeText(selected.template); setCopied(true); }

  return <main className="friend-sim">
    <header className="friend-sim-nav"><Link href="/">← REACH Action Hub</Link><Link href="/reach-a-friend">Friend support guide</Link></header>
    {!selected && <><section className="friend-sim-hero"><div className="friend-sim-hero-copy"><p className="kicker">AN INTERACTIVE REACH EXPERIENCE</p><h1>Help them stay.</h1><p>Your friend says they may leave college. Practice what to say, see how your response lands, and leave with words and resources you can use in real life.</p><a href="#choose-a-path" className="button primary">Begin the conversation ↓</a></div><div className="friend-cast" aria-label="Nia and Jordan, the student characters in this experience"><div className="cast-card nia"><img src="/reach-nia.png" alt="Nia, a supportive college friend"/><span><b>Nia</b>You choose what she says.</span></div><div className="cast-card jordan"><img src="/reach-jordan.png" alt="Jordan, a college student facing a difficult semester"/><span><b>Jordan</b>They are thinking about leaving.</span></div></div></section>
    <section className="path-selector" id="choose-a-path"><div className="path-selector-head"><p className="kicker">CHOOSE THE PRESSURE POINT</p><h2>What is pushing Jordan out?</h2><p>Each pathway changes the story, coaching, response template, and resources.</p></div><div className="path-cards">{pathways.map(path => <button key={path.id} className={`path-card ${path.color}`} onClick={() => choosePath(path)}><span>{path.icon}</span><div><h3>{path.label}</h3><p>{path.summary}</p><b>Practice this pathway →</b></div></button>)}</div></section>
    <section className="reach-method"><p className="kicker">THE REACH METHOD</p><h2>You do not have to fix everything.</h2><div>{stages.map((stage, index) => <article key={stage}><span>{index + 1}</span><h3>{stage}</h3><p>{["Notice what changed and choose a calm moment.","Make room for the full story without judgment.","Ask what support they want before solving.","Offer one practical next step and do it together.","Check back specifically within 24–48 hours."][index]}</p></article>)}</div></section></>}
    {selected && !finished && <section className="simulator-shell"><div className="sim-progress"><button onClick={() => setSelected(null)}>← Change pathway</button><div><span style={{width:`${((step + 1) / scenes.length) * 100}%`}} /></div><p>Scene {step + 1} of {scenes.length}</p></div><div className="simulator-grid"><aside className="sim-character"><div className="sim-character-frame"><img src="/reach-jordan.png" alt="Jordan" /></div><span>{selected.label}</span><h2>Jordan</h2><blockquote>“{scenes[step].message}”</blockquote></aside><section className="sim-conversation" aria-live="polite"><p className="kicker">{stages[Math.min(step, stages.length - 1)]}</p><h1>{scenes[step].title}</h1><div className="coach-note"><b>REACH coach</b><p>{scenes[step].coach}</p></div><h2>What should Nia say?</h2><div className="choice-list">{scenes[step].choices.map((choice, index) => <button key={choice.text} onClick={() => picked === null && setPicked(index)} disabled={picked !== null} className={picked === index ? (choice.strong ? "chosen strong" : "chosen rethink") : picked !== null && choice.strong ? "best" : ""}><span>{String.fromCharCode(65 + index)}</span><p>{choice.text}</p></button>)}</div>{picked !== null && <div className={`choice-feedback ${scenes[step].choices[picked].strong ? "strong" : "rethink"}`}><b>{scenes[step].choices[picked].strong ? "That keeps the door open." : "Try a different instinct next time."}</b><p>{scenes[step].choices[picked].feedback}</p><button onClick={next}>{step === scenes.length - 1 ? "Build my support kit →" : "Continue the conversation →"}</button></div>}</section></div></section>}
    {selected && finished && <section className="support-kit"><div className="support-kit-head"><p className="kicker">YOUR REACH SUPPORT KIT</p><h1>You finished the {selected.label.toLowerCase()} pathway.</h1><p>You chose {score} strong response{score === 1 ? "" : "s"} out of {scenes.length}. This is practice, not a grade—the goal is to stay present, protect dignity, and help with one next step.</p><div><button onClick={() => choosePath(selected)}>Replay this pathway</button><button onClick={() => setSelected(null)}>Try another pathway</button></div></div><div className="support-kit-grid"><article className="copy-template"><span>READY-TO-SEND TEMPLATE</span><h2>Words you can use</h2><blockquote>“{selected.template}”</blockquote><button onClick={copyTemplate}>{copied ? "Copied ✓" : "Copy this message"}</button></article><article className="resource-stack"><span>THE NEXT RIGHT CONNECTION</span><h2>Resources for this situation</h2>{selected.resources.map(resource => <a href={resource.href} key={resource.label} target={resource.href.startsWith("http") ? "_blank" : undefined} rel="noreferrer"><b>{resource.label}</b><p>{resource.detail}</p><span>↗</span></a>)}</article></div><div className="followup-card"><div><span>24 HOURS</span><h3>“How are you doing today? Did you want company for that next step?”</h3></div><div><span>48 HOURS</span><h3>“I remembered what you told me. What changed, and what still feels stuck?”</h3></div><p><b>Remember:</b> You can care deeply without becoming the only support person. If safety is at risk, involve trained help immediately.</p></div></section>}
  </main>;
}
