/* eslint-disable @next/next/no-html-link-for-pages */
import Link from "next/link";
import {chatGPTSignInPath,getChatGPTUser} from "@/app/chatgpt-auth";
import {adminEmails} from "@/lib/reach-shipping-admin";
import "./impact.css";

type Row={id:string;tool:string;status:string;school:string|null;amount_cents:number|null;outcome:string;created_at:string};

export default async function ImpactAdmin(){
  const user=await getChatGPTUser();
  if(!user)return <main className="impact-gate"><p>EFF NATIONAL OFFICE</p><h1>REACH Impact</h1><span>Sign in with an authorized National Office account.</span><a href={chatGPTSignInPath("/admin/impact")}>Sign in securely</a></main>;
  if(!adminEmails().has(user.email.toLowerCase()))return <main className="impact-gate"><p>ACCESS NOT AUTHORIZED</p><h1>REACH Impact</h1><span>Signed in as {user.email}. Contact the National Office.</span><Link href="/">Return home</Link></main>;
  let rows:Row[]=[];let error="";try{const {env}=await import("cloudflare:workers");if(env.DB){const result=await env.DB.prepare(`SELECT id,tool,status,school,amount_cents,outcome,created_at FROM student_defense_outcomes ORDER BY created_at DESC LIMIT 500`).all<Row>();rows=result.results||[];}else error="Database binding unavailable.";}catch{error="No outcome table exists yet. It will be created with the first impact check-in.";}
  const resolved=rows.filter((r)=>r.status==="resolved"||r.status==="improved").length;const dollars=rows.reduce((sum,r)=>sum+(r.amount_cents||0),0)/100;const aidRows=rows.filter((r)=>r.tool==="counteroffer"&&(r.amount_cents||0)>0);const aidAverage=aidRows.length?aidRows.reduce((sum,r)=>sum+(r.amount_cents||0),0)/100/aidRows.length:0;const schools=new Set(rows.map((r)=>r.school?.trim().toLowerCase()).filter(Boolean)).size;
  return <main className="impact-admin"><nav><Link href="/">← REACH home</Link><span>Signed in as {user.email}</span><a href="/api/admin/outcomes/export">Download CSV</a></nav><header><p>EFF NATIONAL OFFICE · DE-IDENTIFIED OUTCOMES</p><h1>Movement,<br/><em>measured.</em></h1><span>Self-reported outcomes are shown separately from verified program awards and should not be described as causal impact without review.</span></header><section className="impact-metrics"><article><strong>{rows.length}</strong><span>outcomes reported</span></article><article><strong>{resolved}</strong><span>resolved or improved</span></article><article><strong>{schools}</strong><span>schools represented</span></article><article><strong>{dollars.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0})}</strong><span>money reported protected or added</span></article><article><strong>{aidAverage.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0})}</strong><span>average reported counter-offer gain</span></article></section>{error&&<p className="impact-error">{error}</p>}<section className="impact-table"><header><h2>Latest student outcomes</h2><span>{rows.length} record{rows.length===1?"":"s"}</span></header>{rows.length?<div><table><thead><tr><th>Date</th><th>Tool</th><th>Status</th><th>School</th><th>Amount</th><th>De-identified outcome</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td>{new Date(row.created_at).toLocaleDateString("en-US")}</td><td>{row.tool}</td><td>{row.status.replaceAll("_"," ")}</td><td>{row.school||"—"}</td><td>{row.amount_cents===null?"—":(row.amount_cents/100).toLocaleString("en-US",{style:"currency",currency:"USD"})}</td><td>{row.outcome}</td></tr>)}</tbody></table></div>:<p className="impact-empty">No outcomes have been reported yet.</p>}</section></main>;
}
