"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useEffect, useMemo, useState } from "react";
import RetentionTerminal, { type RetentionCategory } from "./RetentionTerminal";

type ModuleId = "triage" | "tuition" | "sap" | "grade" | "fees" | "employer" | "transcript" | "syllabus" | "degree" | "reverse" | "housing" | "grievance" | "hold" | "receipt";

const modules: { id: ModuleId; code: string; title: string; desc: string; tone: string }[] = [
  { id:"triage", code:"START HERE", title:"What Do I Do First?", desc:"Choose the crisis in front of you and get the safest next door.", tone:"purple" },
  { id:"tuition", code:"ALL RETENTION BARRIERS", title:"College Retention Emergency Terminal", desc:"Tuition, aid, housing, transportation, essentials, courseware, and whole-student support.", tone:"yellow" },
  { id:"sap", code:"KEEP YOUR AID", title:"SAP Appeal Builder", desc:"Organize circumstances, evidence, and a realistic academic recovery plan.", tone:"yellow" },
  { id:"grade", code:"DO THE MATH", title:"Grade Rescue Calculator", desc:"See the average you need on remaining work—without panic math.", tone:"blue" },
  { id:"fees", code:"AUDIT THE BILL", title:"Bursar Fee Review", desc:"Scan a text-based bill for charges worth questioning or verifying.", tone:"pink" },
  { id:"employer", code:"UNLOCK BENEFITS", title:"Employer Tuition Finder", desc:"Find an official education-benefit path and build the HR request.", tone:"lavender" },
  { id:"transcript", code:"RELEASE CREDITS", title:"Transcript Hold Navigator", desc:"Check the federal baseline and draft a precise records request.", tone:"yellow" },
  { id:"syllabus", code:"SEE RED WEEKS", title:"Syllabus Collision Map", desc:"Pull dated work into one workload map before deadlines collide.", tone:"blue" },
  { id:"degree", code:"PROTECT THE PATH", title:"Course Sequence Checker", desc:"Map prerequisites and term-only courses that may delay graduation.", tone:"pink" },
  { id:"reverse", code:"RECOVER CREDIT", title:"Reverse Transfer Navigator", desc:"Build the request that may turn completed credits into a credential.", tone:"lavender" },
  { id:"housing", code:"PROTECT HOME", title:"Housing Evidence Builder", desc:"Document a deposit, repair, fee, or entry dispute before escalating.", tone:"yellow" },
  { id:"grievance", code:"DOCUMENT IT", title:"Grade Grievance Builder", desc:"Compare the syllabus, decision, and policy using a clean fact record.", tone:"blue" },
  { id:"hold", code:"UNDER $500", title:"Micro-Hold Rescue", desc:"Build the smallest verified plan that protects registration.", tone:"pink" },
  { id:"receipt", code:"KNOW THE NUMBERS", title:"Campus Reality Receipt", desc:"Use federal data to see net price, tuition, and Pell participation.", tone:"purple" },
];

export default function DefenseSuite() {
  const [active, setActive] = useState<ModuleId>("triage");
  const [retentionCategory, setRetentionCategory] = useState<RetentionCategory>("tuition");
  useEffect(() => {
    const requested = new URLSearchParams(window.location.search).get("tool") as ModuleId | null;
    if (requested && modules.some((module) => module.id === requested)) queueMicrotask(() => setActive(requested));
  }, []);
  const choose = (id: ModuleId) => { setActive(id); window.history.replaceState({}, "", `/defense?tool=${id}`); window.scrollTo({ top: 700, behavior:"smooth" }); };
  const openRetention = (category: RetentionCategory) => { setRetentionCategory(category); setActive("tuition"); window.history.replaceState({}, "", `/defense?tool=tuition&category=${category}`); window.scrollTo({ top: 700, behavior:"smooth" }); };

  return <>
    <section className="defense-hero">
      <div><p className="defense-kicker">THE SYSTEM BETWEEN “I’M STUCK” AND “I KNOW MY NEXT MOVE”</p><h1>Protect your aid.<br/><em>Protect your path.</em></h1><p>Focused tools for the financial, academic, administrative, and basic-needs barriers that push students out of college.</p><div><button onClick={() => choose("triage")}>Tell us what is happening →</button><a href="https://portal.estherfundsfoundation.org/resources/student-help">I need a real person</a></div></div>
      <aside><span>PRIVATE BY DEFAULT</span><strong>No account needed.</strong><p>Drafts and calculations stay in your browser unless you choose to open a secure EFF help case.</p><small>Never upload an SSN, password, full bank number, or unredacted ID.</small></aside>
    </section>
    <section className="defense-principles"><span><b>01</b> Find the exact barrier</span><span><b>02</b> Separate facts from fear</span><span><b>03</b> Build the document</span><span><b>04</b> Escalate to the right office</span></section>
    <section className="defense-shell">
      <header><p className="defense-kicker">CHOOSE YOUR ENGINE</p><h2>One problem. One clear workflow.</h2><p>These tools prepare decisions and requests. Schools, employers, courts, funders, and EFF staff make their own final determinations.</p></header>
      <div className="defense-module-grid">{modules.map((module) => <button key={module.id} className={`${module.tone} ${active === module.id ? "active" : ""}`} onClick={() => choose(module.id)}><small>{module.code}</small><strong>{module.title}</strong><span>{module.desc}</span></button>)}</div>
      <section className="defense-workspace">
        {active === "triage" && <Triage choose={choose} openRetention={openRetention}/>}
        {active === "tuition" && <RetentionTerminal initialCategory={retentionCategory}/>}
        {active === "sap" && <SapAppeal/>}
        {active === "grade" && <GradeRescue/>}
        {active === "fees" && <FeeReview/>}
        {active === "employer" && <EmployerBenefit/>}
        {active === "transcript" && <TranscriptHold/>}
        {active === "syllabus" && <SyllabusMap/>}
        {active === "degree" && <CourseSequence/>}
        {active === "reverse" && <ReverseTransfer/>}
        {active === "housing" && <HousingEvidence/>}
        {active === "grievance" && <GradeGrievance/>}
        {active === "hold" && <MicroHold/>}
        {active === "receipt" && <CampusReceipt/>}
      </section>
    </section>
  </>;
}

function Panel({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: React.ReactNode }) {
  return <article className="defense-panel"><header><p className="defense-kicker">{eyebrow}</p><h2>{title}</h2><p>{intro}</p></header>{children}</article>;
}

function Field({ label, value, set, placeholder, area=false, type="text", wide=false }: { label:string; value:string; set:(value:string)=>void; placeholder?:string; area?:boolean; type?:string; wide?:boolean }) {
  return <label className={`defense-field${wide?" wide":""}`}><span>{label}</span>{area?<textarea value={value} onChange={(event)=>set(event.target.value)} placeholder={placeholder}/>:<input type={type} value={value} onChange={(event)=>set(event.target.value)} placeholder={placeholder}/>}</label>;
}

function Select({ label, value, set, options, wide=false }: { label:string; value:string; set:(value:string)=>void; options:[string,string][]; wide?:boolean }) {
  return <label className={`defense-field${wide?" wide":""}`}><span>{label}</span><select value={value} onChange={(event)=>set(event.target.value)}>{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>;
}

function Draft({ title, text, note="Review every fact, follow the recipient’s instructions, and keep a copy of what you send." }: { title:string; text:string; note?:string }) {
  const [copied,setCopied]=useState(false);
  const copy=async()=>{try{await navigator.clipboard.writeText(text);setCopied(true);window.setTimeout(()=>setCopied(false),1800);}catch{setCopied(false)}};
  return <section className="defense-draft"><div><small>READY TO REVIEW</small><h3>{title}</h3><button onClick={copy}>{copied?"Copied ✓":"Copy draft"}</button></div><pre>{text}</pre><p>{note}</p></section>;
}

function Triage({ choose, openRetention }: { choose:(id:ModuleId)=>void; openRetention:(category:RetentionCategory)=>void }) {
  const paths:[string,string,string,ModuleId | "external",string][]=[
    ["Tuition, bill, or hold","A balance, unexpected charge, aid gap, course-drop warning, or registration block.","money","tuition","Open enrollment defense"],
    ["Financial aid eligibility","Unposted aid, PLUS denial, income change, verification, or office delays.","aid","tuition","Open regulatory aid defense"],
    ["Failing or falling behind","A grade feels impossible or several deadlines hit at once.","academic","grade","Calculate the next move"],
    ["Food, housing, or transportation","An essential need is making enrollment unstable.","needs","tuition","Open immediate-needs defense"],
    ["It’s late and I’m overwhelmed","I need to slow the panic down before I decide anything.","spirit","external","Enter Selah"],
  ];
  const go=(kind:string,id:ModuleId|"external")=>{
    if(id!=="external") {
      if (id === "tuition") {
        const category: RetentionCategory = kind === "aid" ? "financial_aid" : kind === "needs" ? "essentials" : "tuition";
        openRetention(category);
        return;
      }
      choose(id);
      return;
    }
    window.location.assign(kind==="spirit"?"https://portal.estherfundsfoundation.org/resources/selah":"https://portal.estherfundsfoundation.org/resources/student-help");
  };
  return <Panel eyebrow="INTAKE · 30 SECONDS" title="What is putting school at risk right now?" intro="Choose the most urgent barrier. If your immediate safety is at risk, call 911. If you are in emotional crisis or thinking about suicide, call or text 988."><div className="triage-grid">{paths.map(([title,desc,kind,id,cta])=><button key={title} onClick={()=>go(kind,id)}><span>{kind.toUpperCase()}</span><strong>{title}</strong><p>{desc}</p><b>{cta} →</b></button>)}</div><div className="defense-links"><a href="tel:988">Call or text 988</a><a href="https://www.211.org/">Find local help through 211</a><a href="https://mentor.estherfundsfoundation.org/">Find an EFF mentor</a></div></Panel>;
}

function SapAppeal() {
  const [v,setV]=useState({name:"",school:"",issue:"gpa",notice:"",circumstance:"work",facts:"",changes:"",plan:"",deadline:""});
  const u=(key:keyof typeof v,value:string)=>setV({...v,[key]:value});
  const label=v.issue==="pace"?"pace-of-completion requirement":v.issue==="time"?"maximum-timeframe requirement":"qualitative GPA requirement";
  const circumstance=({work:"a significant change in work responsibilities",family:"a death, illness, or urgent family responsibility",medical:"a medical, mental-health, or disability-related circumstance",needs:"food, housing, transportation, childcare, or another basic-needs disruption",other:"another documented special circumstance"} as Record<string,string>)[v.circumstance];
  const draft=`Subject: Satisfactory Academic Progress Appeal — ${v.name||"[student name]"}\n\nDear Financial Aid Appeals Committee:\n\nI am requesting reconsideration of my financial-aid eligibility under ${v.school||"[school]"}’s Satisfactory Academic Progress policy. The notice I received concerns the ${label}${v.notice?`: ${v.notice}`:""}. I understand that the school’s written policy and appeal requirements control this decision.\n\nDuring the affected period, I experienced ${circumstance}. ${v.facts||"[Add the dates, facts, and direct academic effect. Do not exaggerate or include unrelated private details.]"}\n\nThe circumstances have changed, or I now have supports in place: ${v.changes||"[Explain what is different now.]"} My academic recovery plan is to ${v.plan||"[List specific actions, contacts, frequency, and measurable checkpoints.]"}\n\nI respectfully request review of my appeal and, if approved, written confirmation of any probation terms or academic plan I must follow. I have attached the school’s required form and relevant documentation. Please let me know if anything else is needed before ${v.deadline||"[deadline]"}.\n\nSincerely,\n${v.name||"[student name]"}\n[student ID — only in the school’s secure system]`;
  return <Panel eyebrow="FINANCIAL AID DEFENSE" title="Build a truthful SAP appeal." intro="Federal rules require schools to publish their own SAP policy. The school—not this tool—sets the appeal process, evidence rules, GPA standard, and pace calculation."><div className="defense-grid"><Field label="Student name" value={v.name} set={(x)=>u("name",x)}/><Field label="School" value={v.school} set={(x)=>u("school",x)}/><Select label="What part of SAP was not met?" value={v.issue} set={(x)=>u("issue",x)} options={[["gpa","GPA / qualitative standard"],["pace","Completion pace"],["time","Maximum timeframe"]]}/><Field label="Appeal deadline" value={v.deadline} set={(x)=>u("deadline",x)} placeholder="Include time zone"/><Field wide label="Copy the exact notice language" value={v.notice} set={(x)=>u("notice",x)} area/><Select label="Main documented circumstance" value={v.circumstance} set={(x)=>u("circumstance",x)} options={[["work","Work hours or duties changed"],["family","Death, illness, or family emergency"],["medical","Medical, mental health, or disability"],["needs","Basic-needs disruption"],["other","Other special circumstance"]]}/><Field wide area label="What happened, when, and how did it affect coursework?" value={v.facts} set={(x)=>u("facts",x)} placeholder="Use a short factual timeline."/><Field wide area label="What has changed or been addressed?" value={v.changes} set={(x)=>u("changes",x)} placeholder="Example: reduced shifts, treatment started, childcare secured, accessibility meeting scheduled"/><Field wide area label="Specific academic recovery plan" value={v.plan} set={(x)=>u("plan",x)} placeholder="Example: tutoring Tuesdays, adviser check-in every two weeks, reduced course load approved by aid office"/></div><div className="evidence-strip"><b>Evidence checklist</b><span>School SAP notice and policy</span><span>Required appeal form</span><span>Short timeline</span><span>Relevant documentation</span><span>Academic plan or adviser note</span></div><Draft title="SAP appeal draft" text={draft}/><div className="defense-links"><a href="https://fsapartners.ed.gov/knowledge-center/fsa-handbook/fsa-assessments/satisfactory-academic-progress">Official federal SAP framework ↗</a><a href="https://portal.estherfundsfoundation.org/resources/student-help">Open an EFF help case ↗</a></div></Panel>;
}

function GradeRescue() {
  const [v,setV]=useState({grade:"",completed:"",target:"70",finalWeight:"",days:""});
  const n=(x:string)=>Number(x)||0; const completed=Math.min(Math.max(n(v.completed),0),100); const remaining=100-completed; const needed=remaining>0?(n(v.target)-n(v.grade)*(completed/100))/(remaining/100):Infinity;
  const status=!v.grade||!v.completed?"Enter your current grade and completed course weight.":needed<=0?"You have already secured the target based on the numbers entered.":needed>100?"The target is not mathematically reachable through the remaining graded work alone.":`You need an average of ${needed.toFixed(1)}% across the remaining ${remaining.toFixed(1)}% of the course.`;
  const finalNeeded=useMemo(()=>{const fw=n(v.finalWeight);if(!fw||fw>remaining)return null;const other=remaining-fw;const assumed=Math.min(Math.max(needed,0),100);return (n(v.target)-n(v.grade)*(completed/100)-assumed*(other/100))/(fw/100)},[v,completed,remaining,needed]);
  return <Panel eyebrow="ACADEMIC TRIAGE" title="Replace panic with the actual math." intro="Use the weights in the official syllabus and the current grade shown in the gradebook. Ask the instructor whether ungraded work is already counted as zero."><div className="defense-grid"><Field label="Current course grade" value={v.grade} set={(x)=>setV({...v,grade:x})} placeholder="Example: 64"/><Field label="Percent of course already graded" value={v.completed} set={(x)=>setV({...v,completed:x})} placeholder="Example: 60"/><Field label="Target final course grade" value={v.target} set={(x)=>setV({...v,target:x})}/><Field label="Final exam weight (optional)" value={v.finalWeight} set={(x)=>setV({...v,finalWeight:x})} placeholder="Example: 25"/><Field label="Days until the next major deadline" value={v.days} set={(x)=>setV({...v,days:x})} placeholder="Example: 8"/></div><section className={`grade-result ${needed>100?"danger":needed<=100&&v.grade&&v.completed?"possible":""}`}><small>THE NUMBER THAT MATTERS</small><strong>{Number.isFinite(needed)&&v.grade&&v.completed?`${needed.toFixed(1)}%`:"—"}</strong><p>{status}</p>{finalNeeded!==null&&<span>If all other remaining work averages {Math.min(Math.max(needed,0),100).toFixed(1)}%, the final would also need about {finalNeeded.toFixed(1)}%. Change the assumptions with your instructor before relying on this.</span>}</section><ol className="action-list"><li>Confirm the current grade, remaining weights, late-work rules, and missing assignments in the official syllabus and gradebook.</li><li>Prioritize the highest-weight work that is still accepted; do not skip an assignment based on a calculator alone.</li><li>Email the instructor early with one specific question and a proposed plan.</li><li>If illness, disability, caregiving, or a documented emergency is involved, contact the appropriate campus office now.</li></ol></Panel>;
}

type FeeLine={label:string;amount:number;reason:string};
function FeeReview() {
  const [text,setText]=useState(""); const [name,setName]=useState(""); const [status,setStatus]=useState("Upload a text-based PDF or paste an itemized bill.");
  const lines=useMemo<FeeLine[]>(()=>text.split(/\r?\n/).map((line)=>line.trim()).filter(Boolean).map((line)=>{const match=line.match(/\$\s*([\d,]+(?:\.\d{1,2})?)/);const amount=match?Number(match[1].replaceAll(",","")):0;let reason="";if(/health.*insurance|student.*insurance/i.test(line))reason="Ask whether proof of other coverage permits a waiver.";else if(/inclusive access|digital.*book|course material|textbook/i.test(line))reason="Ask whether there is an opt-out deadline and how required materials would be obtained.";else if(/transport|parking|transit/i.test(line))reason="Ask whether the charge is mandatory for your enrollment type or campus.";else if(/recreation|athletic|activity fee/i.test(line))reason="Ask for the published mandatory-fee policy and any approved exception process.";else if(/late fee|penalty/i.test(line))reason="Ask whether an aid delay or documented hardship supports a one-time review.";return {label:line,amount,reason};}).filter((line)=>line.reason),[text]);
  const total=lines.reduce((sum,line)=>sum+line.amount,0);
  const read=async(file?:File)=>{if(!file)return;setName(file.name);setStatus("Scanning the document locally…");try{let value="";if(file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")){const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const content=await page.getTextContent();value+=content.items.map((item)=>"str" in item?`${item.str}${item.hasEOL?"\n":" "}`:"").join("")+"\n";}}else value=await file.text();setText(value);setStatus("Scan complete. Review every detected line against the original bill.");}catch{setStatus("This file may be scanned or protected. Paste the itemized text below instead.");}};
  const draft=`Subject: Request for itemized fee review\n\nHello Student Accounts Team,\n\nI am requesting a written review of the following charges on my student account:\n\n${lines.length?lines.map((line)=>`• ${line.label}`).join("\n"):"[Paste the exact charge names and amounts.]"}\n\nPlease confirm whether each charge is mandatory for my enrollment, the published policy that authorizes it, any waiver or opt-out criteria, the deadline and required documentation, and how removing an optional charge would affect services or enrollment. I am not disputing a valid charge without review; I am asking for the itemized rule and available process in writing.\n\nThank you,\n[student name]\n[student ID in the secure school portal only]`;
  return <Panel eyebrow="STUDENT ACCOUNTS DEFENSE" title="Scan the bill. Question the right lines." intro="A detected charge is not automatically illegal or waivable. This tool flags common categories for a documented policy review."><label className="defense-drop"><input type="file" accept=".pdf,.txt,application/pdf,text/plain" onChange={(event)=>read(event.target.files?.[0])}/><span>↑</span><strong>Choose an itemized bill</strong><small>Text-based PDF or TXT · processed in this browser</small></label><p className="scan-status">{name&&<b>{name}: </b>}{status}</p><Field wide area label="Or paste the itemized charges" value={text} set={setText} placeholder="Example: Student Health Insurance $1,850"/><div className="scan-hud"><span className={text?"done":""}>Scanning for student health insurance…</span><span className={text?"done":""}>Detecting digital textbook and course-material charges…</span><span className={text?"done":""}>Reviewing transportation, activity, and late-fee lines…</span></div><section className="fee-results"><header><div><small>REVIEW CANDIDATES</small><h3>{lines.length} line{lines.length===1?"":"s"} detected</h3></div><strong>${total.toLocaleString()}</strong></header>{lines.length?<div>{lines.map((line)=><article key={line.label}><b>{line.label}</b><p>{line.reason}</p></article>)}</div>:<p>No review categories detected yet. Paste the exact itemized text; absence of a match does not mean every charge is mandatory.</p>}</section><Draft title="Fee-review email package" text={draft}/></Panel>;
}

function EmployerBenefit() {
  const [v,setV]=useState({employer:"other",company:"",program:"",school:"",course:"",start:"",status:"",contact:""});
  const u=(key:keyof typeof v,value:string)=>setV({...v,[key]:value});
  const company=v.employer==="walmart"?"Walmart":v.employer==="starbucks"?"Starbucks":v.company||"[employer]";
  const official=v.employer==="walmart"?{title:"Walmart Live Better U",href:"https://corporate.walmart.com/about/working-at-walmart/live-better-u",copy:"Walmart describes Live Better U as its education-benefit program. Eligibility, covered programs, and current terms must be confirmed through Walmart’s official associate channels."}:v.employer==="starbucks"?{title:"Starbucks education opportunity",href:"https://www.starbucksbenefits.com/en-us/home/education-opportunity/",copy:"Starbucks publishes education opportunities for eligible partners. Confirm current eligibility, school, program, and service requirements in the official benefits portal."}:{title:"IRS educational-assistance overview",href:"https://www.irs.gov/publications/p15b",copy:"A written employer educational-assistance program may provide up to $5,250 in tax-free benefits under federal rules, but an employer is not required to offer it and its plan controls eligibility."};
  const draft=`Subject: Request for education-benefit eligibility and enrollment steps\n\nHello ${v.contact||"Benefits or Human Resources Team"}:\n\nI am a ${v.status||"[full-time/part-time]"} employee of ${company} and would like written information about any tuition assistance, educational assistance, scholarship, reimbursement, or partner-school program available to me.\n\nI am considering ${v.course||"[degree, certificate, or course]"} at ${v.school||"[school]"}, beginning ${v.start||"[date]"}. Please confirm:\n\n• whether I am currently eligible;\n• whether this school and program are covered;\n• whether approval is required before enrollment or payment;\n• grade, service-time, work-status, and continued-employment requirements;\n• annual and lifetime limits;\n• whether payment is direct or reimbursed; and\n• the official application deadline and portal.\n\nI will not enroll in reliance on the benefit until I receive and review the current plan terms. Thank you.\n\nSincerely,\n[employee name]`;
  return <Panel eyebrow="EARN + LEARN" title="Find tuition money already attached to work." intro="Search official employer benefits before paying out of pocket. A federal tax rule is not a promise that your employer offers a benefit."><div className="defense-grid"><Select label="Employer shortcut" value={v.employer} set={(x)=>u("employer",x)} options={[["other","Another employer"],["walmart","Walmart"],["starbucks","Starbucks"]]}/>{v.employer==="other"&&<Field label="Employer name" value={v.company} set={(x)=>u("company",x)}/>}<Field label="Job status" value={v.status} set={(x)=>u("status",x)} placeholder="Part-time, full-time, seasonal"/><Field label="HR or benefits contact" value={v.contact} set={(x)=>u("contact",x)} placeholder="If known"/><Field label="School" value={v.school} set={(x)=>u("school",x)}/><Field label="Degree, certificate, or course" value={v.course} set={(x)=>u("course",x)}/><Field label="Expected start date" value={v.start} set={(x)=>u("start",x)}/><Field wide area label="What the employer portal says (optional)" value={v.program} set={(x)=>u("program",x)} placeholder="Paste only nonprivate benefit details"/></div><section className="source-card"><small>OFFICIAL STARTING POINT</small><h3>{official.title}</h3><p>{official.copy}</p><a href={official.href}>Open official information ↗</a></section><Draft title="HR education-benefit request" text={draft}/><div className="defense-links"><a href="https://www.irs.gov/newsroom/irs-updates-frequently-asked-questions-about-section-127-educational-assistance-programs">IRS Section 127 FAQ ↗</a></div></Panel>;
}

function TranscriptHold() {
  const [v,setV]=useState({name:"",school:"",balance:"",aid:"unknown",paid:"unknown",period:"",request:"transfer",agreement:"",deadline:""});
  const u=(key:keyof typeof v,value:string)=>setV({...v,[key]:value});
  const draft=`Subject: Written transcript-release review — ${v.name||"[student name]"}\n\nHello Registrar and Student Accounts Teams:\n\nI am requesting a written review of my transcript access at ${v.school||"[school]"}. I need the record for ${v.request==="employment"?"employment":v.request==="reenroll"?"reenrollment":"transfer or continued education"}${v.deadline?` by ${v.deadline}`:""}. My account shows an estimated balance of ${v.balance?`$${v.balance}`:"[amount]"}.\n\nPlease identify in writing:\n1. the exact charge and payment period connected to the hold;\n2. whether Title IV federal aid was received for that payment period;\n3. which credits or clock hours can be released under current federal requirements;\n4. whether a current payment arrangement changes transcript access; and\n5. the school policy and appeal or review process that applies.\n\n${v.agreement?`Payment-plan context: ${v.agreement}\n\n`:""}I understand that federal requirements may apply only to certain payment periods and do not necessarily require release of every part of a record. Please send the available transcript or explain the remaining restriction and next review step.\n\nThank you,\n${v.name||"[student name]"}\n[student ID through the secure school portal only]`;
  return <Panel eyebrow="RELEASE COMPLETED CREDIT" title="Ask for the part of your transcript the rule protects." intro="Since July 1, 2024, federal rules restrict transcript withholding for certain payment periods. The facts of the charges, aid, and payment arrangement matter."><div className="defense-grid"><Field label="Student name" value={v.name} set={(x)=>u("name",x)}/><Field label="School" value={v.school} set={(x)=>u("school",x)}/><Field label="Estimated balance" value={v.balance} set={(x)=>u("balance",x)} placeholder="Numbers only"/><Field label="Relevant payment period" value={v.period} set={(x)=>u("period",x)} placeholder="Example: Fall 2025"/><Select label="Federal Title IV aid received then?" value={v.aid} set={(x)=>u("aid",x)} options={[["unknown","I need the school to confirm"],["yes","Yes"],["no","No"]]}/><Select label="Institutional charges paid?" value={v.paid} set={(x)=>u("paid",x)} options={[["unknown","I need the school to confirm"],["yes","Yes"],["agreement","Current payment agreement"],["no","Not fully paid"]]}/><Select label="Why the transcript is needed" value={v.request} set={(x)=>u("request",x)} options={[["transfer","Transfer or continued education"],["reenroll","Reenrollment"],["employment","Employment"]]}/><Field label="Deadline" value={v.deadline} set={(x)=>u("deadline",x)}/><Field wide area label="Payment agreement or account context" value={v.agreement} set={(x)=>u("agreement",x)}/></div><section className="law-note"><b>Federal baseline—not a blanket debt cancellation.</b><p>A school generally must provide an official transcript containing credits or clock hours for payment periods in which the student received Title IV aid and all institutional charges for that period were paid or covered by a current agreement to repay. Ask the school to apply the rule to each payment period.</p></section><Draft title="Transcript-access review request" text={draft}/><div className="defense-links"><a href="https://fsapartners.ed.gov/knowledge-center/fsa-handbook/2024-2025/vol2/ch3-fsa-administrative-and-related-requirements">Official Federal Student Aid handbook ↗</a><a href="https://portal.estherfundsfoundation.org/resources/student-help">Open an EFF help case ↗</a></div></Panel>;
}

type DeadlineItem={course:string;date:string;task:string};
function SyllabusMap() {
  const [text,setText]=useState(""); const [work,setWork]=useState(""); const [status,setStatus]=useState("Paste the dated assignment lines from each syllabus.");
  const items=useMemo<DeadlineItem[]>(()=>text.split(/\r?\n/).map((line)=>line.trim()).filter(Boolean).map((line)=>{const parts=line.split("|").map((x)=>x.trim());if(parts.length<3)return null;const date=new Date(parts[1]);if(Number.isNaN(date.getTime()))return null;return {course:parts[0],date:date.toISOString().slice(0,10),task:parts.slice(2).join(" | ")};}).filter((x):x is DeadlineItem=>Boolean(x)).sort((a,b)=>a.date.localeCompare(b.date)),[text]);
  const weeks=useMemo(()=>{const grouped=new Map<string,DeadlineItem[]>();for(const item of items){const date=new Date(`${item.date}T12:00:00`);const day=(date.getDay()+6)%7;date.setDate(date.getDate()-day);const key=date.toISOString().slice(0,10);grouped.set(key,[...(grouped.get(key)||[]),item]);}return [...grouped.entries()];},[items]);
  const read=async(file?:File)=>{if(!file)return;setStatus("Reading dates locally…");try{let value="";if(file.type==="application/pdf"||file.name.endsWith(".pdf")){const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const content=await page.getTextContent();value+=content.items.map((item)=>"str" in item?`${item.str}${item.hasEOL?"\n":" "}`:"").join("")+"\n";}}else value=await file.text();setText(value);setStatus("Document read. Because syllabi format dates differently, convert important lines to COURSE | YYYY-MM-DD | TASK below.");}catch{setStatus("The file could not be read. Paste the dated lines instead.");}};
  return <Panel eyebrow="DEADLINE COLLISION RADAR" title="See the hard weeks before they arrive." intro="Put every major due date in one format. The map flags density; it does not decide what to skip."><label className="defense-drop"><input type="file" accept=".pdf,.txt" onChange={(event)=>read(event.target.files?.[0])}/><span>↑</span><strong>Choose a syllabus PDF or TXT</strong><small>Processed in this browser</small></label><p className="scan-status">{status}</p><Field wide area label="One item per line: COURSE | YYYY-MM-DD | TASK" value={text} set={setText} placeholder="BIO 101 | 2026-09-18 | Unit exam&#10;ENG 102 | 2026-09-19 | Research paper"/><Field wide label="Work, care, or commute constraints" value={work} set={setWork} placeholder="Example: Work Mon/Wed/Fri 4–10 PM"/><section className="week-map">{weeks.length?weeks.map(([week,list])=><article className={list.length>=3?"collision":""} key={week}><header><small>WEEK OF</small><strong>{week}</strong><span>{list.length>=3?"COLLISION RISK":`${list.length} major item${list.length===1?"":"s"}`}</span></header>{list.map((item)=><p key={`${item.course}-${item.date}-${item.task}`}><b>{item.date} · {item.course}</b>{item.task}</p>)}</article>):<p>No structured dates yet.</p>}</section>{weeks.some(([,list])=>list.length>=3)&&<Draft title="Early workload conversation" text={`Subject: Planning ahead for a high-volume academic week\n\nHello [instructor/adviser]:\n\nI am planning ahead for the week of [date], when several major assignments or exams are scheduled across my courses. I am not asking to avoid course requirements. I would like to confirm the due date, format, and available preparation supports for [specific item] so I can begin early.\n\nMy current constraint is: ${work||"[brief schedule constraint]"}. Please let me know whether office hours, tutoring, a study guide, or another approved support is available.\n\nThank you,\n[student name]`}/>}</Panel>;
}

type CourseNode={code:string;terms:string[];prereqs:string[]};
function CourseSequence() {
  const [text,setText]=useState(""); const [completed,setCompleted]=useState("");
  const nodes=useMemo<CourseNode[]>(()=>text.split(/\r?\n/).map((line)=>line.trim()).filter(Boolean).map((line)=>{const [code="",terms="",prereqs=""]=line.split("|").map((x)=>x.trim());return {code:code.toUpperCase(),terms:terms.toLowerCase().split(",").map((x)=>x.trim()).filter(Boolean),prereqs:prereqs.toUpperCase().split(",").map((x)=>x.trim()).filter(Boolean)};}).filter((x)=>x.code),[text]);
  const done=useMemo(()=>new Set(completed.toUpperCase().split(/[,\n]/).map((x)=>x.trim()).filter(Boolean)),[completed]);
  const problems=useMemo(()=>{const codes=new Set(nodes.map((x)=>x.code));const missing=nodes.flatMap((node)=>node.prereqs.filter((pre)=>!codes.has(pre)&&!done.has(pre)).map((pre)=>`${node.code} requires ${pre}, which is not listed as completed or planned.`));const limited=nodes.filter((node)=>node.terms.length===1).map((node)=>`${node.code} is entered as ${node.terms[0]}-only; missing it may add a term.`);const cycles:string[]=[];const visiting=new Set<string>(),visited=new Set<string>();const byCode=new Map(nodes.map((x)=>[x.code,x]));const visit=(code:string,path:string[])=>{if(visiting.has(code)){cycles.push(`Prerequisite cycle entered: ${[...path,code].join(" → ")}`);return;}if(visited.has(code))return;visiting.add(code);for(const pre of byCode.get(code)?.prereqs||[])visit(pre,[...path,code]);visiting.delete(code);visited.add(code);};nodes.forEach((node)=>visit(node.code,[]));return [...new Set([...missing,...limited,...cycles])];},[nodes,done]);
  return <Panel eyebrow="DEGREE PATH DEFENSE" title="Find the course that can delay three others." intro="Build a quick map from the official catalog and degree audit. Course availability changes, so confirm the final plan with an academic adviser."><Field wide area label="One course per line: CODE | offered terms | prerequisite codes" value={text} set={setText} placeholder="BIO 101 | fall,spring |&#10;BIO 201 | spring | BIO 101&#10;BIO 301 | fall | BIO 201"/><Field wide area label="Completed course codes, separated by commas" value={completed} set={setCompleted} placeholder="ENC 1101, MAT 1033"/><div className="sequence-grid">{nodes.map((node)=><article key={node.code}><small>{node.terms.join(" + ")||"TERM UNKNOWN"}</small><strong>{node.code}</strong><span>{node.prereqs.length?`After ${node.prereqs.join(", ")}`:"No prerequisite entered"}</span></article>)}</div><section className="risk-list"><h3>Items to verify</h3>{problems.length?problems.map((problem)=><p key={problem}>⚠ {problem}</p>):<p>Enter the official sequence. No issues are flagged yet.</p>}</section><div className="defense-links"><a href="https://portal.estherfundsfoundation.org/resources/student-help">Ask EFF for planning support ↗</a></div></Panel>;
}

function ReverseTransfer() {
  const [v,setV]=useState({name:"",current:"",prior:"",credits:"",last:"",state:"",degree:"associate degree"});
  const u=(key:keyof typeof v,value:string)=>setV({...v,[key]:value});
  const draft=`Subject: Reverse-transfer eligibility and transcript-exchange request\n\nHello Registrar or Completion Team:\n\nMy name is ${v.name||"[student name]"}. I previously attended ${v.prior||"[prior two-year institution]"} and now attend ${v.current||"[current institution]"}. I completed approximately ${v.credits||"[number]"} credits at the prior institution and last attended in ${v.last||"[term/year]"}.\n\nI would like to know whether I may be eligible for reverse transfer or another credential-completion review for an ${v.degree}. Please confirm:\n\n• whether the institutions participate in a reverse-transfer or transcript-exchange process;\n• whether I must provide consent before records are exchanged;\n• residency, minimum-credit, GPA, and catalog requirements;\n• whether any missing course could be completed at my current institution; and\n• whether there are transcript, balance, graduation-application, or deadline requirements.\n\nI understand that sending credits does not guarantee a credential. Please provide the official next step and form.\n\nThank you,\n${v.name||"[student name]"}`;
  return <Panel eyebrow="CREDIT RECOVERY" title="Ask whether completed credits already add up to a credential." intro="Reverse transfer can allow a former two-year student to send later credits back for an associate-degree review. Participation and rules vary by institution and state."><div className="defense-grid"><Field label="Student name" value={v.name} set={(x)=>u("name",x)}/><Field label="State" value={v.state} set={(x)=>u("state",x)}/><Field label="Current college" value={v.current} set={(x)=>u("current",x)}/><Field label="Prior two-year college" value={v.prior} set={(x)=>u("prior",x)}/><Field label="Approximate prior credits" value={v.credits} set={(x)=>u("credits",x)}/><Field label="Last term at prior college" value={v.last} set={(x)=>u("last",x)}/></div><div className="evidence-strip"><b>Ask both schools</b><span>Do you participate?</span><span>Is consent required?</span><span>Which catalog applies?</span><span>Is a balance blocking records?</span></div><Draft title="Reverse-transfer review request" text={draft}/></Panel>;
}

function HousingEvidence() {
  const [v,setV]=useState({name:"",issue:"deposit",property:"",city:"",state:"",date:"",facts:"",request:"",deadline:""});
  const u=(key:keyof typeof v,value:string)=>setV({...v,[key]:value});
  const label=({deposit:"security deposit",repair:"repair or habitability concern",fee:"housing fee",entry:"entry or notice concern"} as Record<string,string>)[v.issue];
  const draft=`Subject: Written notice and request regarding ${label}\n\nHello ${v.property||"[housing provider or campus housing office]"}:\n\nI am writing to document a ${label} concerning [address or unit] in ${v.city||"[city]"}, ${v.state||"[state]"}. The relevant date is ${v.date||"[date]"}.\n\nFacts in chronological order:\n${v.facts||"[State only what you personally observed, the dates, who was contacted, and what response was received.]"}\n\nRequested resolution:\n${v.request||"[State the specific repair, itemization, refund review, notice, or written response requested.]"}\n\nPlease acknowledge receipt and respond in writing${v.deadline?` by ${v.deadline}`:" within the applicable policy or legal timeframe"}. I am preserving the lease, notices, photographs, receipts, and communications. This message is a factual request and does not waive any rights or remedies.\n\nThank you,\n${v.name||"[name]"}`;
  return <Panel eyebrow="HOUSING EVIDENCE LAB" title="Build the record before the argument." intro="Housing rules depend on the lease, campus policy, city, and state. This tool organizes facts; it is not legal advice or a substitute for a local attorney."><div className="defense-grid"><Field label="Your name" value={v.name} set={(x)=>u("name",x)}/><Select label="Issue" value={v.issue} set={(x)=>u("issue",x)} options={[["deposit","Security deposit"],["repair","Repair or habitability"],["fee","Housing fee"],["entry","Entry or notice"]]}/><Field label="Housing provider or campus office" value={v.property} set={(x)=>u("property",x)}/><Field label="City" value={v.city} set={(x)=>u("city",x)}/><Field label="State" value={v.state} set={(x)=>u("state",x)}/><Field label="Key date" value={v.date} set={(x)=>u("date",x)}/><Field label="Response deadline" value={v.deadline} set={(x)=>u("deadline",x)}/><Field wide area label="Factual timeline" value={v.facts} set={(x)=>u("facts",x)} placeholder="Date · event · person contacted · response"/><Field wide area label="Specific resolution requested" value={v.request} set={(x)=>u("request",x)}/></div><div className="evidence-strip"><b>Preserve</b><span>Lease and policies</span><span>Dated photos/video</span><span>Receipts</span><span>Emails and notices</span><span>Inspection records</span></div><Draft title="Housing documentation notice" text={draft}/><div className="defense-links"><a href="https://www.lsc.gov/about-lsc/what-legal-aid/get-legal-help">Find civil legal aid ↗</a><a href="https://www.hud.gov/states">HUD resources by state ↗</a></div></Panel>;
}

function GradeGrievance() {
  const [v,setV]=useState({name:"",school:"",course:"",instructor:"",decision:"",syllabus:"",policy:"",records:"",request:""});
  const u=(key:keyof typeof v,value:string)=>setV({...v,[key]:value});
  const draft=`Subject: Request for review under the published grade-appeal process — ${v.course||"[course]"}\n\nHello ${v.instructor||"[instructor or reviewing administrator]"}:\n\nI am requesting a review of ${v.decision||"[the specific grade or academic decision]"} in ${v.course||"[course]"} at ${v.school||"[school]"}. I am using the school’s published process and am not requesting a grade based only on disagreement.\n\nThe syllabus or written course standard states:\n${v.syllabus||"[Quote or accurately summarize the relevant grading rule.]"}\n\nThe published review policy states:\n${v.policy||"[Add the policy, step, and deadline.]"}\n\nMy records show:\n${v.records||"[List dated submissions, gradebook entries, rubrics, and prior communications.]"}\n\nI respectfully request ${v.request||"[a calculation check, rubric review, correction of a record, or the specific remedy allowed by policy]"}. Please let me know the next formal step and deadline.\n\nThank you,\n${v.name||"[student name]"}`;
  return <Panel eyebrow="ACADEMIC RECORD" title="Turn a grade dispute into a policy-based review." intro="Start with the syllabus, gradebook, rubric, and school appeal policy. Keep the request factual, specific, and within the deadline."><div className="defense-grid"><Field label="Student name" value={v.name} set={(x)=>u("name",x)}/><Field label="School" value={v.school} set={(x)=>u("school",x)}/><Field label="Course" value={v.course} set={(x)=>u("course",x)}/><Field label="Instructor or reviewer" value={v.instructor} set={(x)=>u("instructor",x)}/><Field wide area label="Exact grade or decision" value={v.decision} set={(x)=>u("decision",x)}/><Field wide area label="Relevant syllabus or rubric language" value={v.syllabus} set={(x)=>u("syllabus",x)}/><Field wide area label="Published appeal policy and deadline" value={v.policy} set={(x)=>u("policy",x)}/><Field wide area label="Dated records" value={v.records} set={(x)=>u("records",x)}/><Field wide area label="Specific remedy requested" value={v.request} set={(x)=>u("request",x)}/></div><Draft title="Grade-review request" text={draft}/></Panel>;
}

function MicroHold() {
  const [v,setV]=useState({amount:"",school:"",type:"registration",deadline:"",charge:"",verified:"unknown",resources:"",contact:""});
  const u=(key:keyof typeof v,value:string)=>setV({...v,[key]:value});const amount=Number(v.amount)||0;
  const draft=`Subject: Urgent verified plan for ${v.type} hold${v.deadline?` before ${v.deadline}`:""}\n\nHello ${v.contact||"Student Accounts or Student Support Team"}:\n\nMy account at ${v.school||"[school]"} shows a ${v.type} hold connected to ${v.charge||"[exact charge]"}, currently estimated at ${v.amount?`$${amount.toFixed(2)}`:"[amount]"}. Please confirm the exact balance, charge, deadline, and action required to remove or temporarily resolve the hold.\n\nI am trying to protect my enrollment and would like review for the smallest safe option available, including an institutional emergency or completion grant, approved payment arrangement, documented hardship review, short-term campus fund, or other school process. Available resources I can verify are: ${v.resources||"[amount and date, or none]"}.\n\nPlease do not process a payment or enrollment change without my authorization. Send the available options, terms, and consequences in writing.\n\nThank you,\n[student name]`;
  return <Panel eyebrow="SMALL BALANCE · BIG CONSEQUENCE" title="Rescue a hold without making a dangerous promise." intro="Verify the charge first. This tool does not pay a balance, issue a card, promise EFF funding, or authorize a payment plan."><div className="defense-grid"><Field label="Hold amount" value={v.amount} set={(x)=>u("amount",x)} placeholder="Numbers only"/><Field label="School" value={v.school} set={(x)=>u("school",x)}/><Select label="What the hold blocks" value={v.type} set={(x)=>u("type",x)} options={[["registration","Registration"],["transcript","Transcript"],["graduation","Graduation"],["housing","Housing"],["other","Another service"]]}/><Field label="Deadline" value={v.deadline} set={(x)=>u("deadline",x)}/><Field wide label="Exact charge name" value={v.charge} set={(x)=>u("charge",x)}/><Select label="Amount verified with the school?" value={v.verified} set={(x)=>u("verified",x)} options={[["unknown","Not yet"],["yes","Yes, in writing"],["no","The amounts conflict"]]}/><Field label="Office or contact" value={v.contact} set={(x)=>u("contact",x)}/><Field wide area label="Money already available, if any" value={v.resources} set={(x)=>u("resources",x)} placeholder="Do not enter bank or card numbers"/></div><section className={`hold-meter ${amount>500?"over":""}`}><small>HOLD SIZE</small><strong>{v.amount?`$${amount.toFixed(2)}`:"—"}</strong><p>{!v.amount?"Enter the verified amount.":amount<=500?"This fits the micro-hold workflow. Protect the deadline while requesting the smallest verified solution.":"This exceeds $500. Use the broader Tuition Rescue Plan and contact the school immediately."}</p></section><Draft title="Hold-resolution request" text={draft}/><div className="defense-links"><a href="/tools/balance">Open Tuition Rescue Plan</a><a href="https://portal.estherfundsfoundation.org/resources/student-help">Open a secure EFF help case ↗</a></div></Panel>;
}

type ScorecardSchool={id:number;name:string;state:string;netPrice:number|null;tuitionInState:number|null;tuitionOutOfState:number|null;pellRate:number|null};
function CampusReceipt() {
  const [query,setQuery]=useState("");const [results,setResults]=useState<ScorecardSchool[]>([]);const [selected,setSelected]=useState<ScorecardSchool|null>(null);const [status,setStatus]=useState("Search by the school’s official name.");
  const search=async()=>{if(query.trim().length<3){setStatus("Enter at least three letters.");return;}setStatus("Checking the U.S. Department of Education College Scorecard…");setSelected(null);try{const response=await fetch(`/api/scorecard?q=${encodeURIComponent(query)}`);const data=await response.json() as {results?:ScorecardSchool[];error?:string};if(!response.ok)throw new Error(data.error);setResults(data.results||[]);setStatus(data.results?.length?"Choose the correct campus.":"No matching institution was returned.");}catch(error){setResults([]);setStatus(error instanceof Error?error.message:"Official data is temporarily unavailable.");}};
  const fmt=(value:number|null)=>value===null?"Not reported":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
  return <Panel eyebrow="OFFICIAL SCHOOL CONTEXT" title="Get the campus reality receipt." intro="This receipt uses federally published institution-level figures. It is context—not your personal bill, aid offer, or a ranking of school quality."><div className="search-row"><Field label="College or university" value={query} set={setQuery} placeholder="Enter the official school name"/><button onClick={search}>Search official data</button></div><p className="scan-status" aria-live="polite">{status}</p>{results.length>0&&<div className="school-results">{results.map((school)=><button key={school.id} onClick={()=>setSelected(school)}><strong>{school.name}</strong><span>{school.state}</span></button>)}</div>}{selected&&<section className="receipt"><header><small>COLLEGE SCORECARD SNAPSHOT</small><h3>{selected.name}</h3><p>{selected.state} · Institution ID {selected.id}</p></header><div><article><small>AVERAGE NET PRICE</small><strong>{fmt(selected.netPrice)}</strong><p>Average annual net price for aided undergraduates in the reported federal data—not your bill.</p></article><article><small>IN-STATE TUITION</small><strong>{fmt(selected.tuitionInState)}</strong><p>Published tuition figure; required fees and living costs may be separate.</p></article><article><small>OUT-OF-STATE TUITION</small><strong>{fmt(selected.tuitionOutOfState)}</strong><p>Confirm residency classification directly with the school.</p></article><article><small>PELL RECIPIENT SHARE</small><strong>{selected.pellRate===null?"Not reported":`${Math.round(selected.pellRate*100)}%`}</strong><p>Share of undergraduates receiving Pell Grants in the reported data.</p></article></div><footer><p>Ask the school: What is my exact net price after grants? What is billed now? Which costs are estimates? Which aid must be repaid or earned?</p><a href={`https://collegescorecard.ed.gov/school/?${selected.id}`}>Open the official College Scorecard ↗</a></footer></section>}<div className="defense-links"><a href="/tools/award">Decode my actual aid letter</a><a href="/tools/counteroffer">Compare competing offers</a><a href="https://collegescorecard.ed.gov/data/api-documentation/">College Scorecard data documentation ↗</a></div></Panel>;
}
