/* National and EFF resources for REACH Get Help. Copied from MyEFF's
   lib/reach-resources.ts (every outside address there was checked against the
   organisation's own site on 29 Sept 2026). Keep the two lists in step. */
export type ReachResource = {
  key: string; name: string; what: string; href: string; cta: string;
  group: "eff" | "money" | "food" | "mind" | "career"; outside?: boolean; letter: string;
};

export const RESOURCES: ReachResource[] = [
  /* EFF */
  { key: "reach", name: "REACH Action Hub", what: "Scholarships, emergency support, a stay-enrolled plan, cost-gap tools and guided next steps in one place.", href: "https://reach.estherfundsfoundation.org/", cta: "Open REACH", group: "eff", letter: "A" },
  { key: "helpdesk", name: "Ask EFF for help", what: "Tell a real person at EFF what's going on: financial aid, billing, housing, registration, anything. You get a code to follow your request.", href: "https://my.estherfundsfoundation.org/lighthouse", cta: "Ask EFF", group: "eff", letter: "R" },
  { key: "portal", name: "REACH Scholarships", what: "Thousands of open scholarships, checked every morning, plus EFF's own. Get matched in two minutes.", href: "https://reach.estherfundsfoundation.org/scholarships", cta: "Find scholarships", group: "money", letter: "A" },
  { key: "lighthouse", name: "The Lighthouse", what: "Ask EFF National for help privately, and follow your lantern until a person has it.", href: "/lighthouse", cta: "Ask for help", group: "eff", letter: "R" },
  { key: "food", name: "REACH Emergency Food Request", what: "For currently enrolled college students facing an urgent food emergency. Requests are reviewed by urgency and available resources.", href: "https://form.jotform.com/262448222885060", cta: "Request food help", group: "food", letter: "A" },
  { key: "walk", name: "The Scholarship Walk", what: "167 scholarships for high school, undergraduate, graduate and international students, in the order they close. Save a list and add deadlines to your calendar.", href: "https://reach.estherfundsfoundation.org/scholarshipwalk", cta: "Take the walk", group: "money", letter: "A" },
  { key: "match", name: "Scholarship Match", what: "Answer a few questions and see the open scholarships that fit you, with the reasons why.", href: "https://reach.estherfundsfoundation.org/scholarships/match", cta: "Take the quiz", group: "money", letter: "A" },
  { key: "resume", name: "EFF Builds Your Resume", what: "A free tool that builds a stronger, more professional resume with you.", href: "https://reach.estherfundsfoundation.org/eff-builds-your-resume/", cta: "Build your resume", group: "career", letter: "A" },
  { key: "interview", name: "EFF Interview Coach", what: "A free eight-question mock interview with instant coaching.", href: "https://reach.estherfundsfoundation.org/eff-interview-coach/", cta: "Practice an interview", group: "career", letter: "A" },
  { key: "letters", name: "The Letter Desk", what: "A personal recommendation letter written and signed by EFF National, sealed with a link any school can check.", href: "/letters", cta: "Ask for a letter", group: "career", letter: "A" },
  { key: "selah", name: "Selah", what: "EFF's quiet space: soft music, a verse, a timer and a grounding exercise when your mind is loud.", href: "https://selah.estherfundsfoundation.org/", cta: "Take a breath", group: "mind", letter: "C" },
  { key: "chapters", name: "Find your EFF chapter", what: "A community on your campus that will notice when you go quiet.", href: "/chapters", cta: "Find a chapter", group: "eff", letter: "E" },
  { key: "join", name: "Join EFF", what: "A national membership is a full membership, whether or not your campus has a chapter yet.", href: "/join", cta: "Join EFF", group: "eff", letter: "E" },

  { key: "kit", name: "The Survival Kit", what: "Can I still register? Write my appeal. Help near my campus. REACH's four tools for the night it feels like you're done.", href: "/kit", cta: "Open the kit", group: "eff", letter: "A" },

  /* outside, official and national */
  { key: "pellprotector", name: "Pell Protector", what: "From 2026–27, grants and scholarships from your state, college or a private group that reach your cost of attendance end your Pell Grant for the year. Check where you stand, in English or Spanish. Nothing you type is saved.", href: "/kit/pell", cta: "Check my Pell", group: "money", letter: "A" },
  { key: "pell", name: "Federal Pell Grants", what: "Federal grants for students with financial need. Unlike loans, they generally don't have to be paid back.", href: "https://studentaid.gov/understand-aid/types/grants/pell", cta: "About Pell Grants", group: "money", letter: "A", outside: true },
  { key: "scholarshipsgov", name: "Finding scholarships (StudentAid.gov)", what: "Where to look, when scholarship season is, and how to apply without missing a deadline.", href: "https://studentaid.gov/understand-aid/types/scholarships", cta: "Read the tips", group: "money", letter: "A", outside: true },
  { key: "ftc", name: "Avoid scholarship scams (FTC)", what: "The warning signs: guaranteed awards, fees to apply, requests for your card or bank number. Report scams at 1-877-FTC-HELP.", href: "https://consumer.ftc.gov/articles/how-avoid-scholarship-and-financial-aid-scams", cta: "Know the red flags", group: "money", letter: "A", outside: true },
  { key: "loans", name: "Subsidized vs. unsubsidized loans", what: "Which federal loans charge interest while you're in school, and which don't.", href: "https://studentaid.gov/articles/subsidized-vs-unsubsidized-loans/", cta: "Compare loans", group: "money", letter: "A", outside: true },
  { key: "notenough", name: "Didn't get enough aid?", what: "StudentAid.gov's options when your financial aid doesn't cover the bill.", href: "https://studentaid.gov/articles/financial-aid-not-enough/", cta: "See the options", group: "money", letter: "A", outside: true },
  { key: "cfpb", name: "Manage your college money (CFPB)", what: "Free tools from the Consumer Financial Protection Bureau, including a spending tracker and tips to avoid overdraft fees.", href: "https://www.consumerfinance.gov/consumer-tools/student-loans/manage-your-college-money/", cta: "Get the tools", group: "money", letter: "A", outside: true },
  { key: "nimh5", name: "5 action steps (NIMH)", what: "Ask, be there, help keep them safe, help them connect, follow up: what to do when someone may be thinking about suicide.", href: "https://www.nimh.nih.gov/health/publications/5-action-steps-to-help-someone-having-thoughts-of-suicide", cta: "Learn the five steps", group: "mind", letter: "H", outside: true },
  { key: "nimhsigns", name: "Warning signs of suicide (NIMH)", what: "What to listen for and watch for, from the National Institute of Mental Health.", href: "https://www.nimh.nih.gov/sites/default/files/documents/health/publications/warning-signs-of-suicide/warning-signs-of-suicide.pdf", cta: "Know the signs", group: "mind", letter: "C", outside: true },
  { key: "sleep", name: "How much sleep you need (CDC)", what: "Adults 18 to 60 need at least 7 hours a night. Why it matters for your mood, memory and health.", href: "https://www.cdc.gov/sleep/about/index.html", cta: "About sleep", group: "mind", letter: "C", outside: true },

  { key: "fafsa", name: "FAFSA at StudentAid.gov", what: "The free federal application for grants, work-study and loans. File every year. It never costs money to file.", href: "https://studentaid.gov/h/apply-for-aid/fafsa", cta: "Open the FAFSA", group: "money", letter: "A", outside: true },
  { key: "fsaphone", name: "Federal Student Aid help line", what: "Stuck on the FAFSA? Call 1-800-4-FED-AID (1-800-433-3243) and a person walks you through it.", href: "tel:18004333243", cta: "Call the help line", group: "money", letter: "R", outside: true },
  { key: "careeronestop", name: "CareerOneStop Scholarship Finder", what: "The U.S. Department of Labor's free search of more than 9,500 scholarships, grants and fellowships. No account needed.", href: "https://www.careeronestop.org/Toolkit/Training/find-scholarships.aspx", cta: "Search scholarships", group: "money", letter: "A", outside: true },
  { key: "uncf", name: "UNCF scholarships", what: "The nation's largest private scholarship provider, with hundreds of programs for students at UNCF member colleges and beyond.", href: "https://uncf.org/scholarships", cta: "See UNCF scholarships", group: "money", letter: "A", outside: true },
  { key: "tmcf", name: "Thurgood Marshall College Fund scholarships", what: "Scholarships for students at public HBCUs and Predominantly Black Institutions. One profile matches you to what you qualify for.", href: "https://tmcf.org/scholarships/", cta: "See TMCF scholarships", group: "money", letter: "A", outside: true },
  { key: "hsf", name: "Hispanic Scholarship Fund", what: "Scholarships and support for Hispanic and Latino students.", href: "https://www.hsf.net/", cta: "Visit HSF", group: "money", letter: "A", outside: true },
  { key: "snap", name: "SNAP for college students (USDA)", what: "The federal rules for when a college student can get SNAP food benefits.", href: "https://www.fns.usda.gov/snap/eligibility/student", cta: "Read the rules", group: "food", letter: "A", outside: true },
  { key: "snapstate", name: "Apply for SNAP in your state", what: "Every state runs its own SNAP application. Find yours here.", href: "https://www.fns.usda.gov/snap/state-directory", cta: "Find my state", group: "food", letter: "A", outside: true },
  { key: "findhelp", name: "findhelp.org", what: "Type your ZIP code to find free and low-cost food, housing, health care, transit and more near you.", href: "https://www.findhelp.org/", cta: "Search by ZIP", group: "food", letter: "A", outside: true },
  { key: "swipe", name: "Swipe Out Hunger", what: "The national nonprofit working to end college hunger, with a network of more than 1,000 campuses.", href: "https://swipehunger.org/students/", cta: "For students", group: "food", letter: "E", outside: true },
  { key: "lifeline", name: "Lifeline phone and internet discount", what: "A federal monthly discount on phone or internet if you get SNAP or Medicaid, or your income qualifies.", href: "https://www.lifelinesupport.org/", cta: "Check if I qualify", group: "food", letter: "A", outside: true },
  { key: "211", name: "211", what: "Call or text 211, or search online, for local help with food, rent, utilities and more.", href: "https://www.211.org/", cta: "Find local help", group: "food", letter: "A", outside: true },
  { key: "988", name: "988 Suicide & Crisis Lifeline", what: "Call or text 988, any hour, if you or a friend are in crisis. Free and confidential.", href: "tel:988", cta: "Call 988", group: "mind", letter: "C", outside: true },
  { key: "text", name: "Crisis Text Line", what: "Text HOME to 741741 to reach a trained crisis counselor by text.", href: "sms:741741?&body=HOME", cta: "Text HOME", group: "mind", letter: "C", outside: true },
  { key: "steve", name: "The Steve Fund: text STEVE", what: "For students of color: text STEVE to 741741 to reach a trained crisis counselor, any hour.", href: "sms:741741?&body=STEVE", cta: "Text STEVE", group: "mind", letter: "C", outside: true },
  { key: "trevor", name: "The Trevor Project", what: "For LGBTQ+ young people under 25: call 1-866-488-7386 or text START to 678-678, any hour, free and confidential.", href: "https://www.thetrevorproject.org/get-help/", cta: "Get help now", group: "mind", letter: "C", outside: true },
  { key: "awkward", name: "Seize the Awkward", what: "How to start the conversation when a friend is struggling: what to say, what to ask, and what to do after.", href: "https://seizetheawkward.org/conversation/starting-the-conversation", cta: "Learn what to say", group: "mind", letter: "H", outside: true },
];

/* MyEFF paths are relative there; here they need the full address. */
export const fullHref = (href: string) => (href.startsWith("/") ? `https://my.estherfundsfoundation.org${href}` : href);
export const byKey = (key: string) => RESOURCES.find((r) => r.key === key);
