"use client";

import {FormEvent,useState} from "react";

const tools=[
  ["counteroffer","Financial Aid Counter-Offer Engine"],["recommendation","Recommendation Letter Builder"],["sap","SAP Appeal Builder"],["grade","Grade Rescue Calculator"],["fees","Bursar Fee Review"],["employer","Employer Tuition Finder"],["transcript","Transcript Hold Navigator"],["syllabus","Syllabus Collision Map"],["degree","Course Sequence Checker"],["reverse","Reverse Transfer Navigator"],["housing","Housing Evidence Builder"],["grievance","Grade Grievance Builder"],["hold","Micro-Hold Rescue"],["receipt","Campus Reality Receipt"],["award","Award Letter & Balance Decoder"],["other","Another REACH resource"],
];
const statuses=[["resolved","Resolved"],["improved","Improved, but not fully resolved"],["pending","Submitted or requested—waiting"],["no_change","No change yet"],["referred","Connected to another resource"]];

export default function OutcomeForm(){
  const [form,setForm]=useState({tool:"counteroffer",status:"resolved",school:"",amount:"",outcome:"",consent:false,website:""});
  const [state,setState]=useState<{tone:string;message:string}>({tone:"",message:""});
  const set=(key:string,value:string|boolean)=>setForm({...form,[key]:value});
  const submit=async(event:FormEvent)=>{event.preventDefault();setState({tone:"working",message:"Saving your outcome…"});try{const response=await fetch("/api/outcomes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await response.json() as {ok?:boolean;reference?:string;error?:string};if(!response.ok)throw new Error(data.error||"Please try again.");setState({tone:"success",message:`Thank you—your impact check-in was saved. Reference ${data.reference}.`});setForm({...form,school:"",amount:"",outcome:"",consent:false});}catch(error){setState({tone:"error",message:error instanceof Error?error.message:"Please try again."});}};
  return <section className="outcome-form-shell"><form onSubmit={submit}><div className="outcome-grid"><label><span>Which tool or resource did you use?</span><select value={form.tool} onChange={(e)=>set("tool",e.target.value)}>{tools.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Where is the situation now?</span><select value={form.status} onChange={(e)=>set("status",e.target.value)}>{statuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>School (optional)</span><input value={form.school} onChange={(e)=>set("school",e.target.value)} placeholder="College or university"/></label><label><span>Money protected or added (optional)</span><div><b>$</b><input type="number" min="0" max="100000" step="0.01" value={form.amount} onChange={(e)=>set("amount",e.target.value)} placeholder="0"/></div></label><label className="wide"><span>What changed? Keep it brief and remove private details.</span><textarea required minLength={10} maxLength={800} value={form.outcome} onChange={(e)=>set("outcome",e.target.value)} placeholder="Example: My school reviewed the competing offer and added a $2,000 institutional grant."/></label></div><label className="outcome-consent"><input type="checkbox" checked={form.consent} onChange={(e)=>set("consent",e.target.checked)} required/><span>I confirm this is truthful and EFF may include it in de-identified, aggregate impact reporting. EFF must ask separately before using my words as a public story.</span></label><label className="outcome-honey" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={form.website} onChange={(e)=>set("website",e.target.value)}/></label><button className="outcome-submit" disabled={state.tone==="working"}>Submit my outcome →</button>{state.message&&<p className={`outcome-status ${state.tone}`} aria-live="polite">{state.message}</p>}<p className="outcome-privacy"><b>Please do not enter:</b> your name, email, student ID, Social Security number, account number, medical details, password, or verification code.</p></form><aside><small>WHAT EFF CAN MEASURE</small><h2>Not clicks.<br/>Real movement.</h2><ul><li>Additional non-loan aid secured</li><li>Holds and balances resolved</li><li>Aid and credits protected</li><li>Students connected to support</li><li>Cases still waiting for action</li></ul><p>Every number is reported as a student outcome—not a guarantee that the tool caused it.</p></aside></section>;
}
